### ISSUE TITLE
In iOS 8.1 (iPhone 5, 6) Menu main button is not working, anyone have fixed or solution.  In other devices even in iPhone 4s is working fine, kindly give me solution for iphone 5 and 6,

### ISSUE THREAD

**Issue by muhammad-adnan** [codrops/MultiLevelPushMenu#20]
Hi 
I am facing the problem In iOS 8.1 (iPhone 5, 6) Menu main button is not working, anyone have fixed or solution.  In other devices even in iPhone 4s is working fine, kindly give me solution for iphone 5 and 6 how button will start working

thanks in advance

**Comment by davidbelle** [comment]
I had the same issue and was able to fix it by changing the line 98 in js/mlpushmenu.js from

this.eventtype = mobilecheck() ? 'touchstart' : 'click';

 to

this.eventtype = 'click';
