### ISSUE TITLE
Close menu on link click

### ISSUE THREAD

**Issue by ex0b1t** [codrops/MultiLevelPushMenu#25]
Need a built in function to close menu items. I implement the following hack to close menu items when clicked.

``` javascript
// Hack to close items when clicked
$('.mp-close').mousedown(function () {
    $('body').click();
});
```

**Comment by giolvani** [comment]
@ex0b1t your hack works fine, but no for mobile devices.

In this case, you can use a method from lib:

``` javascript
var menu = new mlPushMenu(.....);
menu._resetMenu();
```
