### ISSUE TITLE
Navigation Menu does not open on mobile

### ISSUE THREAD

**Issue by dennzo** [codrops/MultiLevelPushMenu#34]
Hello together,

I have implemented this wonderful function on my website. In the desktop version I have solved all the problems myself. But on the mobile version, there is one issue where I am not able to find any solution.

[https://digital-admins.com/](https://digital-admins.com)

In the mobile version of my site you are not able to open the left navigation menu.
You can rightclick my site and view the page source. The css and js file is linked in the header/footer.

If somebody could find my problem, this would be very helpful!
Thanks very much in advance!

best regards
Dennis

**Comment by jhonNumpaque** [comment]
Hi..
```
<div class="navbar-header col-sm-2">
                    <!-- Inicio de botón -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main">
                        <span class="sr-only">Menú de Navegación</span>
                        <span class="glyphicon glyphicon-menu-hamburger"></span>                            
                        <!-- Cierre de navegación -->
                    </button>
                    <a class="navbar-brand  toggle-btn" href="#"> <span style="font-size:16px;" class="pull-right hidden-xs showopacity"></span></a>
                    <!-- Cierre de cabezera de nav -->
                </div>
<div id="main" class="collapse navbar-collapse">
 //Code main bar
</div>
```

Examples:....
http://bootsnipp.com/snippets/featured/side-menu-on-hover
http://bootsnipp.com/tags/menu

**Comment by dennzo** [comment]
Hey,

thanks for your fast answer. Unfortunately that is not what I really want.
All I really need is, that the menu opens from the left side (not the top), just as shown in the MultiLevelPushMenu demo.

But Thanks anyway!
